rootstrap/ios-base

README.md

1. Added license and travis badges.
2. Fixed typos in README.md

Added badges and fixed typos

---

ios-base/Base.lproj/Main.storyboard

Disabling autocorrection on the email fields that appears in the sign up and sign in screens

disabling autocorrection on the email 

---

.swiftlint.yml
AcceptanceTests/KIFExtensions.swift

* Fixes repeated code issue from CodeClimate. 
* Updated Swiftlint deprecated rule name.

Refactor repeated code

---

Podfile

* Added omit warnings flag to Podfile:
- Removes pod libraries related warnings in XCode and Travis.
---
* Low
---

Add warning flag to podfile

---

ios-base/View/Home/HomeViewController.swift
ios-base/ViewModel/Home/HomeViewModel.swift

refactor HomeViewController/ViewModel to a different MVVM approach, in which the view model updates its state describing the work being done and the view controller is responsible to update its views according to the view model state.
This patterns allows a lighter view controller and gives more responsibility to the view model making it more than an intermediate between the view controller and the service layer.

MVVM approach proposal

---

ios-base/View/Onboarding/SignInViewController.swift
ios-base/View/Onboarding/SignUpViewController.swift
ios-base/ViewModel/Home/HomeViewModel.swift
ios-base/ViewModel/Onboarding/SignInViewModel.swift
ios-base/ViewModel/Onboarding/SignUpViewModel.swift

applying new MVVM pattern to sign in view controller and view model

---

README.md

* Private project should NOT be using the MIT license.

Update readme with licensing instructions

---

ios-base/Networking/APIClient.swift

Change PATCH method to use JSONEncoding as default

---

ios-base/Extensions/DictionaryExtension.swift

Fix error in dictionary += operator

---

ios-base/Model/Session.swift
ios-base/Model/User.swift
ios-base/Networking/APIService.swift

* Removed unnecessary initializers and encode/decode functions, since Codable already synthetizes them for us
Reference: https://www.swiftbysundell.com/basics/codable

Removed unnecessary code from codable clases

---

ios-base/Analytics/AnalyticsManager.swift
ios-base/Analytics/AnalyticsService.swift
ios-base/Analytics/FirebaseAnalyticsService.swift
ios-base/Home/ViewModels/HomeViewModel.swift

Add analytics reset method

---

ios-base.xcodeproj/project.pbxproj

* Removing files that were being bundled for no reason(README.md and ThirdPartyKeys.example.plist)
---
Solves #128

Removed README and plist files from final bundle

---

Gemfile
README.md
fastlane/Appfile
fastlane/Fastfile
ios-base.xcodeproj/xcshareddata/xcschemes/ios-base-develop.xcscheme

Adds basic fastlane setup, with lanes for each target and some basic actions (version bump, automatic changelogs, etc.).
Check the new readme section for more details

Adds Fastlane setup

---

ios-base/Base.lproj/Main.storyboard
ios-base/Extensions/UIImageExtension.swift
ios-base/Managers/ConfigurationManager.swift
ios-base/Networking/APIService.swift
ios-base/Networking/Models/Base64Media.swift
ios-base/Onboarding/ViewModels/FirstViewModel.swift
ios-baseUITests/XCUIApplicationExtension.swift
ios-baseUITests/ios_baseUITests.swift

Add successful, failure and form validation sign in tests.

---

.slather.yml
ios-base.xcodeproj/project.pbxproj
ios-base.xcodeproj/xcshareddata/xcschemes/ios-base-develop.xcscheme
ios-base.xcodeproj/xcshareddata/xcschemes/ios-base-production.xcscheme
ios-base.xcodeproj/xcshareddata/xcschemes/ios-base-staging.xcscheme
ios-baseUnitTests/Extensions/StringExtensionUnitTests.swift
ios-baseUnitTests/Info.plist
ios-baseUnitTests/Services/UserServiceUnitTests.swift

* Adds Unit test target to base project.
* Adds base unit test for main services and manager classes.
---
* Low
---

Add Unit Tests Target

---

Podfile
README.md

* Removed old OHHTTPStubs reference 🙈

Update README removing old branches

---

ios-base/Analytics/AnalyticsManager.swift
ios-baseUITests/ios_baseUITests.swift

Fix services variable type

---

Podfile
README.md

* Updated README to remove old feature branch that it is now an independent library.
---

Update README and Podfile

---

Gemfile
README.md
fastlane/Appfile
fastlane/Fastfile

* Minor changes to Fastlane configuration. Reduced duplicated code and improved comments.
* Included cocoapods in Gemfile for running pod install
* Updated Readme

renamed and streamlined lanes in Fastfile

---

CODEOWNERS

Add new members 🎉 
solves: https://github.com/rootstrap/ios-base/issues/181

Update code owner list

---

README.md
ios-base.xcodeproj/project.pbxproj

* This PR fixes an issue where the `example` GoogleServices plist file was linked to a local file.
---
* Low
---
* N/A

Fix orphan google plist

---

CODEOWNERS

* Update CodeOwners file to current iOS member (January 2022)

Update CodeOwners (Jan 2022)

---

README.md
ios-base.xcodeproj/project.pbxproj
ios-base.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
ios-base/AppDelegate.swift
ios-base/Common/Models/Session.swift
ios-base/Common/Models/User.swift
ios-base/Home/ViewModels/HomeViewModel.swift
ios-base/Home/Views/HomeViewController.swift
ios-base/Managers/SessionManager.swift
ios-base/Managers/UserDataManager.swift
ios-base/Navigators/AppNavigator.swift
ios-base/Networking/Extensions/APIClient+Application.swift
ios-base/Networking/Services/AuthenticationServices.swift
ios-base/Networking/Services/UserServices.swift
ios-base/Onboarding/ViewModels/SignInViewModel.swift
ios-base/Onboarding/ViewModels/SignUpViewModel.swift
ios-base/Onboarding/Views/SignInViewController.swift
ios-base/Onboarding/Views/SignUpViewController.swift

* Migrate services to use concurrency

Migrate services to use concurrency
